# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/review-check
Content-Type: application/json

{
  "requestId": "123e4567-e89b-12d3-a456-426614174000",
  "blogUrl": "https://blog.naver.com/ljh98128/223640339178"
}

###
POST http://127.0.0.1:8000/review-check/response
Accept: application/json
