# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/api/review_check
Content-Type: application/json

{
  "requestId": "123e4567-e89b-12d3-a456-426614174000",
  "blogUrl": "https://blog.naver.com/tkdtkdgns1/223604228666"
}

###
POST http://127.0.0.1:8000/api/review_check/result
Accept: application/json
