# ai-server.yaml
---
# AWS Parameter Store 접근을 위한 ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-server-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${var.role_name}
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      serviceAccountName: ai-server-sa  # AWS 권한을 위한 ServiceAccount 연결
      nodeSelector:
        eks.amazonaws.com/nodegroup: ${NODE_GROUP}
      containers:
      - name: fastapi
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/ai-server-real:${TAG}
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
spec:
  selector:
    app: ai-server
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
