# ai-server.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      nodeSelector:
        node-group: ai-workload
      containers:
      - name: fastapi
        image: ${ECR_IMAGE}  # Jenkins에서 주입
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          value: ${OPENAI_API_KEY}  # Jenkins에서 주입
        - name: BACKEND_URL
          value: ${BACKEND_URL}  # Jenkins에서 주입
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
spec:
  selector:
    app: ai-server
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP